# Generated by Django 4.1.1 on 2022-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
