# Generated by Django 4.1.1 on 2022-09-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
