# Generated by Django 4.1.1 on 2022-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_is_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.CharField(default='', max_length=1275),
        ),
    ]
