# Generated by Django 4.1.1 on 2022-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_game_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='desc',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
