# Generated by Django 4.1.1 on 2022-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_game_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.URLField(default=''),
        ),
    ]
